[listener]
type="socket"

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
port="tcp/22"
services=["ssh-simulator"]


[service.adb]
type="adb"

[[port]]
port="tcp/5555"
services=["adb"]


[service.http]
type="http"

[[port]]
port="tcp/80"
services=["http"]


[channel.console]
type="console"

[channel.elasticsearch]
type="elasticsearch"
url="http://honeypot:honeypot@elasticsearch.local.development/honeytrap"

[[filter]]
channel = ["console", "elasticsearch"]

[[logging]]
output = "stdout"
level = "debug"